In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv('/content/drive/MyDrive/kaggle Files/sentiment/train.txt',sep=";", names=["Comment","Emotion"])
data.tail(3)

Comment  Emotion
15997                     i feel strong and good overall      joy
15998  i feel like this was such a rude comment and i...    anger
15999  i know a lot but i feel so stupid because i ca...  sadness

In [3]:
data.shape

(16000, 2)

In [4]:
data['Emotion'].unique()

array(['sadness', 'anger', 'love', 'surprise', 'fear', 'joy'],
      dtype=object)

In [5]:
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [6]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix

In [9]:
# MultinomialNB
from sklearn.naive_bayes import MultinomialNB

In [10]:
lm = WordNetLemmatizer()

In [11]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [12]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [13]:
nltk.download('omw-1.4')

[nltk_data] Downloading package omw-1.4 to /root/nltk_data...


True

In [14]:
def fn(col):
    corpus = []
    for i in col:
        cmt = re.sub('[^a-zA-Z]',' ',str(i))
        cmt = cmt.lower()
        cmt = cmt.split()
        cmt = [lm.lemmatize(word) for word in cmt if word not in set(stopwords.words('english'))]
        corpus.append(' '.join(str(x) for x in cmt))
    return corpus

In [15]:
corpus = fn(data['Comment'])

In [16]:
cv = CountVectorizer(ngram_range=(1,2))
traindata = cv.fit_transform(corpus)
x = traindata
y = data.Emotion

In [17]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [ ]:
mnb=MultinomialNB()
mnb.fit(x_train,y_train)

MultinomialNB()

In [ ]:
y_pred_mnb=mnb.predict(x_test)
y_pred_mnb

array([4, 0, 4, ..., 4, 2, 4])

In [ ]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix

In [ ]:
print("MultinomialNB accuracy score:\t",metrics.accuracy_score(y_test,y_pred_mnb))
print("MultinomialNB training_data accuracy score:\t",mnb.score(x_train,y_train))
print("MultinomialNB testing_data accuracy score:\t",mnb.score(x_test,y_test))

MultinomialNB accuracy score:	 0.7809375
MultinomialNB training_data accuracy score:	 0.956171875
MultinomialNB testing_data accuracy score:	 0.7809375


In [ ]:
cm_mnb=confusion_matrix(y_test,y_pred_mnb)
cm_mnb

array([[ 284,    7,   51,    0,   99,    0],
       [   9,  248,   62,    1,   82,    1],
       [   1,    2, 1011,    6,   37,    0],
       [   2,    3,  142,   67,   40,    0],
       [   3,    3,   26,    0,  881,    0],
       [   0,   20,   55,    0,   49,    8]])

In [ ]:
print("MultinomialNB Classification Report:\n\n",metrics.classification_report(y_test,y_pred_mnb))

MultinomialNB Classification Report:

               precision    recall  f1-score   support

           0       0.95      0.64      0.77       441
           1       0.88      0.62      0.72       403
           2       0.75      0.96      0.84      1057
           3       0.91      0.26      0.41       254
           4       0.74      0.96      0.84       913
           5       0.89      0.06      0.11       132

    accuracy                           0.78      3200
   macro avg       0.85      0.58      0.62      3200
weighted avg       0.81      0.78      0.75      3200



In [20]:
# LogisticRegression
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [21]:
y_pred_lr=lr.predict(x_test)
y_pred_lr

array([4, 0, 0, ..., 5, 2, 4])

In [ ]:
print("LogisticRegression accuracy score:\t",metrics.accuracy_score(y_test,y_pred_lr))
print("LogisticRegression training_data accuracy score:\t",lr.score(x_train,y_train))
print("LogisticRegression testing_data accuracy score:\t",lr.score(x_test,y_test))

LogisticRegression accuracy score:	 0.9034375
LogisticRegression training_data accuracy score:	 0.997578125
LogisticRegression testing_data accuracy score:	 0.9034375


In [ ]:
cm_lr=confusion_matrix(y_test,y_pred_lr)
cm_lr

array([[ 389,   10,   18,    1,   23,    0],
       [  12,  345,   18,    1,   18,    9],
       [   2,    5, 1008,   27,   14,    1],
       [   1,    2,   58,  192,    1,    0],
       [  21,    9,   16,    1,  865,    1],
       [   0,   24,   10,    0,    6,   92]])

In [ ]:
print("Logistic Regression Classification Report:\n\n",metrics.classification_report(y_test,y_pred_lr))

Logistic Regression Classification Report:

               precision    recall  f1-score   support

           0       0.92      0.88      0.90       441
           1       0.87      0.86      0.86       403
           2       0.89      0.95      0.92      1057
           3       0.86      0.76      0.81       254
           4       0.93      0.95      0.94       913
           5       0.89      0.70      0.78       132

    accuracy                           0.90      3200
   macro avg       0.90      0.85      0.87      3200
weighted avg       0.90      0.90      0.90      3200



In [ ]:
# SVC
from sklearn.svm import SVC
svc=SVC(kernel='linear') 
svc.fit(x_train,y_train)

SVC(kernel='linear')

In [ ]:
y_pred_svc=svc.predict(x_test)
y_pred_svc

array([4, 0, 0, ..., 5, 2, 4])

In [ ]:
from sklearn import metrics
print("SVC accuracy score:\t",metrics.accuracy_score(y_test,y_pred_svc))
print("SVC training_data accuracy score:\t",svc.score(x_train,y_train))
print("SVC testing_data accuracy score:\t",svc.score(x_test,y_test))

SVC accuracy score:	 0.9
SVC training_data accuracy score:	 0.998125
SVC testing_data accuracy score:	 0.9


In [ ]:
cm_svc=confusion_matrix(y_test,y_pred_svc)
cm_svc

array([[404,   8,  10,   2,  16,   1],
       [ 15, 351,   8,   3,  11,  15],
       [  4,   7, 986,  41,  16,   3],
       [  2,   2,  55, 195,   0,   0],
       [ 28,  17,  16,   6, 842,   4],
       [  0,  22,   7,   0,   1, 102]])

In [ ]:
print("SVC Classification Report:\n\n",metrics.classification_report(y_test,y_pred_svc))

SVC Classification Report:

               precision    recall  f1-score   support

           0       0.89      0.92      0.90       441
           1       0.86      0.87      0.87       403
           2       0.91      0.93      0.92      1057
           3       0.79      0.77      0.78       254
           4       0.95      0.92      0.94       913
           5       0.82      0.77      0.79       132

    accuracy                           0.90      3200
   macro avg       0.87      0.86      0.87      3200
weighted avg       0.90      0.90      0.90      3200



In [ ]:
# KNN
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [ ]:
y_pred_knn=knn.predict(x_test)
y_pred_knn

array([2, 4, 0, ..., 0, 0, 4])

In [ ]:
print("K_Nearest Neighbor accuracy score:\t",metrics.accuracy_score(y_test,y_pred_knn))
print("K_Nearest Neighbor training_data accuracy score:\t",knn.score(x_train,y_train))
print("K_Nearest Neighbor testing_data accuracy score:\t",knn.score(x_test,y_test))

K_Nearest Neighbor accuracy score:	 0.5078125
K_Nearest Neighbor training_data accuracy score:	 0.7059375
K_Nearest Neighbor testing_data accuracy score:	 0.5078125


In [ ]:
cm_knn=confusion_matrix(y_test,y_pred_knn)
cm_knn

array([[245,  19,  89,   6,  81,   1],
       [ 82, 155,  74,   4,  73,  15],
       [138,  76, 670,  12, 157,   4],
       [ 43,  17, 109,  39,  46,   0],
       [138,  53, 214,   9, 497,   2],
       [ 27,  26,  27,   2,  31,  19]])

In [ ]:
print("K_Nearest Neighbor Classification Report:\n\n",metrics.classification_report(y_test,y_pred_knn))

K_Nearest Neighbor Classification Report:

               precision    recall  f1-score   support

           0       0.36      0.56      0.44       441
           1       0.45      0.38      0.41       403
           2       0.57      0.63      0.60      1057
           3       0.54      0.15      0.24       254
           4       0.56      0.54      0.55       913
           5       0.46      0.14      0.22       132

    accuracy                           0.51      3200
   macro avg       0.49      0.40      0.41      3200
weighted avg       0.52      0.51      0.50      3200



In [ ]:
# DecisionTreeClassifier
from sklearn.tree import DecisionTreeClassifier 
dtc=DecisionTreeClassifier() 
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:
y_pred_dtc=dtc.predict(x_test)
y_pred_dtc

array([1, 0, 0, ..., 5, 2, 4])

In [ ]:
print("DecisionTreeClassifier accuracy score:\t",metrics.accuracy_score(y_test,y_pred_dtc))
print("DecisionTreeClassifier training_data accuracy score:\t",dtc.score(x_train,y_train))
print("DecisionTreeClassifier testing_data accuracy score:\t",dtc.score(x_test,y_test))

DecisionTreeClassifier accuracy score:	 0.8703125
DecisionTreeClassifier training_data accuracy score:	 0.99828125
DecisionTreeClassifier testing_data accuracy score:	 0.8703125


In [ ]:
cm_dtc=confusion_matrix(y_test,y_pred_dtc)
cm_dtc

array([[389,  20,   7,   3,  21,   1],
       [ 15, 336,   8,   2,  17,  25],
       [  8,  12, 943,  51,  34,   9],
       [  5,   3,  40, 203,   3,   0],
       [ 39,  28,  20,   6, 810,  10],
       [  0,  16,   7,   0,   5, 104]])

In [ ]:
print("DecisionTreeClassifier Classification Report:\n\n",metrics.classification_report(y_test,y_pred_dtc))

DecisionTreeClassifier Classification Report:

               precision    recall  f1-score   support

           0       0.85      0.88      0.87       441
           1       0.81      0.83      0.82       403
           2       0.92      0.89      0.91      1057
           3       0.77      0.80      0.78       254
           4       0.91      0.89      0.90       913
           5       0.70      0.79      0.74       132

    accuracy                           0.87      3200
   macro avg       0.83      0.85      0.84      3200
weighted avg       0.87      0.87      0.87      3200



In [ ]:
# RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(n_estimators=10)
rfc.fit(x_train,y_train)

RandomForestClassifier(n_estimators=10)

In [ ]:
y_pred_rfc=rfc.predict(x_test)
y_pred_rfc

array([1, 0, 0, ..., 5, 2, 4])

In [ ]:
print("RandomForestClassifier accuracy score:\t",metrics.accuracy_score(y_test,y_pred_rfc))
print("RandomForestClassifier training_data accuracy score:\t",rfc.score(x_train,y_train))
print("RandomForestClassifier testing_data accuracy score:\t",rfc.score(x_test,y_test))

RandomForestClassifier accuracy score:	 0.8828125
RandomForestClassifier training_data accuracy score:	 0.9946875
RandomForestClassifier testing_data accuracy score:	 0.8828125


In [ ]:
cm_rfc=confusion_matrix(y_test,y_pred_rfc)
cm_rfc

array([[404,   8,  18,   2,   9,   0],
       [ 18, 331,  16,   1,  22,  15],
       [  9,   8, 998,  23,  17,   2],
       [  4,   1,  62, 181,   6,   0],
       [ 27,   9,  55,   4, 816,   2],
       [  0,  17,  12,   1,   7,  95]])

In [ ]:
print("RandomForestClassifier Classification Report:\n\n",metrics.classification_report(y_test,y_pred_rfc))

RandomForestClassifier Classification Report:

               precision    recall  f1-score   support

           0       0.87      0.92      0.89       441
           1       0.89      0.82      0.85       403
           2       0.86      0.94      0.90      1057
           3       0.85      0.71      0.78       254
           4       0.93      0.89      0.91       913
           5       0.83      0.72      0.77       132

    accuracy                           0.88      3200
   macro avg       0.87      0.83      0.85      3200
weighted avg       0.88      0.88      0.88      3200



In [ ]:
# AdaBoostClassifier
from sklearn.ensemble import AdaBoostClassifier
adaboost=AdaBoostClassifier(learning_rate=1)
adaboost.fit(x_train,y_train)

AdaBoostClassifier(learning_rate=1)

In [ ]:
y_pred_adb=adaboost.predict(x_test)
y_pred_adb

array([2, 2, 2, ..., 1, 2, 2])

In [ ]:
print("AdaBoostClassifier accuracy score:\t",metrics.accuracy_score(y_test,y_pred_adb))
print("AdaBoostClassifier training_data accuracy score:\t",adaboost.score(x_train,y_train))
print("AdaBoostClassifier testing_data accuracy score:\t",adaboost.score(x_test,y_test))

AdaBoostClassifier accuracy score:	 0.349375
AdaBoostClassifier training_data accuracy score:	 0.353125
AdaBoostClassifier testing_data accuracy score:	 0.349375


In [ ]:
cm_adb=confusion_matrix(y_test,y_pred_adb)
cm_adb

array([[   2,    3,  435,    1,    0,    0],
       [   1,   39,  346,    1,   16,    0],
       [   5,    1, 1046,    2,    3,    0],
       [   0,    0,  239,   15,    0,    0],
       [   6,    8,  893,    1,    5,    0],
       [   0,   45,   45,    0,   31,   11]])

In [ ]:
print("AdaBoostClassifier Classification Report:\n\n",metrics.classification_report(y_test,y_pred_adb))

AdaBoostClassifier Classification Report:

               precision    recall  f1-score   support

           0       0.14      0.00      0.01       441
           1       0.41      0.10      0.16       403
           2       0.35      0.99      0.52      1057
           3       0.75      0.06      0.11       254
           4       0.09      0.01      0.01       913
           5       1.00      0.08      0.15       132

    accuracy                           0.35      3200
   macro avg       0.46      0.21      0.16      3200
weighted avg       0.31      0.35      0.21      3200



In [ ]:
conclusion=pd.DataFrame({'Title':['MultinomialNB','Logistic Regression','Support Vector Machine Classification','Random Forest Classifier'],
                         'Training_accuracy':[95,99,99,99],'Testing_accuracy':[78,90,90,88],
                         'Confusion_Matrix_True_Values':[2499,2891,2880,2825]})
conclusion.sort_values("Confusion_Matrix_True_Values",ascending=False)

Title  Training_accuracy  Testing_accuracy  \
1                    Logistic Regression                 99                90   
2  Support Vector Machine Classification                 99                90   
3               Random Forest Classifier                 99                88   
0                          MultinomialNB                 95                78   

   Confusion_Matrix_True_Values  
1                          2891  
2                          2880  
3                          2825  
0                          2499

In [22]:
# ['sadness', 'anger', 'love', 'surprise', 'fear', 'joy'],
def expression_check(prediction_input):
    if prediction_input == 0:
        print("Input statement has ANGER Sentiment.")
    elif prediction_input == 1:
        print("Input statement has FEAR Sentiment.")
    elif prediction_input == 2:
        print("Input statement has JOY Sentiment.")
    elif prediction_input == 3:
        print("Input statement has LOVE Sentiment.")
    elif prediction_input == 4:
        print("Input statement has SADNESS Sentiment.")
    elif prediction_input == 5:
        print("Input statement has SURPRISE Sentiment.")
    else:
        print("Invalid Statement.")

In [23]:
def sentiment_predictor(input):
    input = fn(input)
    transformed_input = cv.transform(input)
    prediction = lr.predict(transformed_input)
    expression_check(prediction)

In [24]:
input1 = ["Sometimes I just want to punch someone in the face."]
sentiment_predictor(input1)

Input statement has ANGER Sentiment.


In [25]:
input2 = ["I bought a new phone and it's so good."]
sentiment_predictor(input2)

Input statement has JOY Sentiment.


In [26]:
input3=["ive been feeling a little burdened lately wasnt sure why that was"]
sentiment_predictor(input3)

Input statement has SADNESS Sentiment.


In [27]:
input4=["i now feel compromised and skeptical of the value of every unit of work i put in"]
sentiment_predictor(input4)

Input statement has FEAR Sentiment.


In [28]:
input5=["i am ever feeling nostalgic about the fireplace i will know that it is still on the property"]
sentiment_predictor(input5)

Input statement has LOVE Sentiment.


In [29]:
input6=["i feel like reds and purples are just so rich and kind of perfect"]
sentiment_predictor(input6)

Input statement has JOY Sentiment.


In [30]:
input7=["i feel just bcoz a fight we get mad to each other n u wanna make a publicity n let the world knows about our fight"]
sentiment_predictor(input7)

Input statement has ANGER Sentiment.


In [31]:
input8=["Not much to write about here, but it does exactly what it's supposed to. filters out the pop sounds. now my recordings are much more crisp. it is one of the lowest prices pop filters on amazon so might as well buy it, they honestly work the same despite their pricing,"]
sentiment_predictor(input8)

Input statement has JOY Sentiment.


In [34]:
input9=['''My product is 2 days late yet there is no response. whenever I call customer care they say, "all agents are busy, try again later" and when I request a call from chat, customer care either gives me a missed call or they don't say anything after I pick up the call. They are making fool out of customers.''']
sentiment_predictor(input9)

Input statement has SADNESS Sentiment.


In [35]:
input10=["Nice product . Delivery on time . Items found similar. Item packaging very nice and beautiful. This app is very nice."]
sentiment_predictor(input10)

Input statement has JOY Sentiment.


In [39]:
input11=[data['Comment'][12]]
print(input11)
sentiment_predictor(input11)

['i think it s the easiest time of year to feel dissatisfied']
Input statement has ANGER Sentiment.


In [42]:
input12=[data['Comment'][10000]]
print(input12)
sentiment_predictor(input12)

['i often feel dissatisfied with such discussions partly because of the persistent everyone is beautiful nonsense but partly because they rarely go past the effects of advertising on body image']
Input statement has ANGER Sentiment.
